### ISSUE TITLE
Things yet to be added, reported by @malgamves

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#102]
Yet to add: 
- [x] Animation on hover for section titles to make it smoother
- [x] Remove img animation on header section 
- [x] Code of conduct section or page
- [x] Social Media links and Icons
- [x] Change text to use DevConZM font
- [x] Add "To partner with is, send us an email at info@devcon.co.zm" at bottom of partners section
_Originally posted by @malgamves in https://github.com/devconzm/devconzm/pull/101#issuecomment-515772504_

**Comment by OlivierJM** [comment]
#11 
and this https://github.com/devconzm/devconzm/issues/11#issuecomment-506206197

**Comment by bgongre** [comment]
When you have a chance can you link the social media you'd like to add? Also, is the "DevConZM" font already in the project files, but not added? I had looked for the font in the project files, but may have just missed it.

**Comment by malgamves** [comment]
Sure, Facebook - https://m.facebook.com/devconzm/
Twitter - https://twitter.com/devcon_zm
LinkedIn - https://www.linkedin.com/company/developer-conference-zambia-19
Email - info@devcon.co.zm

On the fonts, @k9uma would have to ask Kumbu. I won't merge #103 now so you can put in the social media icons in the footer

**Comment by OlivierJM** [comment]
I think we should also start thinking about speakers and tickets, so that those tweets go along with this url devcon.co.zm for all details about the conference.

**Comment by malgamves** [comment]
I think at this point, a router is very necessary. Tickets can be on the home page. But speakers, agenda and coc need dedicated pages.

**Comment by bgongre** [comment]
Do you have a specific code of conduct already written up that will be added to the page/section when it is created? I only see the code of conduct in the project and that seems to only relate to the project itself.

**Comment by malgamves** [comment]
This is something we'd do good to a coc from @bgongre -https://vuejs.london/code-of-conduct

**Comment by malgamves** [comment]
Update on font - its [Keep Calm](https://www.cufonfonts.com/font/keep-calm]

**Comment by bgongre** [comment]
@malgamves I can add the font, just let me know if you'd like it for all the text on the main page and if you'd like it set for the code of conduct page as well.

**Comment by malgamves** [comment]
Hello @bgongre yes for both

**Comment by bgongre** [comment]
The Keep Calm font has been added. It looks like all the items on this list have been completed, they just need to be reviewed and merged to master at this point. I also took care of issue #109 by removing the extra unused code for a new partner.
