### ISSUE TITLE
Add Ticket Section

### ISSUE THREAD

**Issue by k9uma** [devconzm/devconzm#104]
Add Ticket Section with the following information
Link to Quicket Ticket purchase page. Link here: https://qkt.io/I3SHAd
Ticket Categories Include the following
1. Early Bird Ticket
    Price: ZK150
    Runs from 29th July to 19th August 2019
2. Regular Ticket
    Price: ZK250
    Runs from 20th August to 20th September 2019

**Comment by Beardless-sheik** [comment]
Quick one........I'm guessing there's an error here.

Early Bird should be cheaper than regular no? Hence early bird should be K150 and regular K200, right?

**Comment by Beardless-sheik** [comment]
@k9uma ??

**Comment by k9uma** [comment]
> @k9uma ??

Hey dude, thanks for noticing that, I have updated the information

**Comment by Beardless-sheik** [comment]
Cool. On that note I can then take up this issue :-)

**Comment by k9uma** [comment]
> Cool. On that note I can then take up this issue :-)

Make sure to claim it too so no one else picks it up in the meantime
