### ISSUE TITLE
Fix Issue with Partners Section

### ISSUE THREAD

**Issue by k9uma** [devconzm/devconzm#109]
Is this intended? There is a image in the second row...

![Screenshot_2019-08-01 DevConZM19](https://user-images.githubusercontent.com/12296763/62280538-6c5c1900-b44c-11e9-8d29-21d881630fd1.png)

_Originally posted by @k9uma in https://github.com/devconzm/devconzm/pull/108_

**Comment by Yogendra0Sharma** [comment]
@k9uma I think this is already implemented.

**Comment by k9uma** [comment]
> 
> 
> @k9uma I think this is already implemented.

Really? I still see the bug on the site

**Comment by k9uma** [comment]
Okay great thanks
