### ISSUE TITLE
Adding a dedicated Code of Conduct page

### ISSUE THREAD

**Issue by malgamves** [devconzm/devconzm#11]
It's import to have a visible and enforced conference code of conduct. This shows we care about the well-being of our community members. We have a COC that I think @k9uma has. I think its worth having a page dedicated to showing that, 
Thoughts?

**Comment by OlivierJM** [comment]
That is very true, we can have a link from the main page on the site that links to the COC and and the major points of it in the readme..

**Comment by malgamves** [comment]
Yes, that works

**Comment by OlivierJM** [comment]
@allcontributors please @malgamves for ideas

**Comment by OlivierJM** [comment]
@allcontributors please add @malgamves for ideas

**Comment by k9uma** [comment]
This was added to the footer and links to the COC... Is that okay?

**Comment by OlivierJM** [comment]
I think we might need a dedicated code of conduct for the conference not just the repository
here are some examples:
- https://www.oreilly.com/conferences/code-of-conduct.html
- https://confcodeofconduct.com/
- https://www.eso.org/sci/meetings/2018/tcl2018/code.html
- https://merchantriskcouncil.org/about-mrc/attendee-code-of-conduct

**Comment by WillzMu** [comment]
It appears the COC link at the top of the webpage does not link to any resource. And the COC link at the bottom directs to `https://www.devcon.co.zm/CodeOfConduct.js` but has no content

**Comment by malgamves** [comment]
Hey @WillzMu thanks for the catch. That has been fixed now
