### ISSUE TITLE
All contributors not reflecting the newly added contributors

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#111]
**Describe the bug**
The allcontributors bot is not reflecting the new members added, this is an issue caused by manually editing the file

**To Reproduce**
1. call the @allcontributors bot 
2. Ask it to add a contributor e.g: @allcontributors please add @OlivierJM for code
3. Merge the created pull requested
4. Check the total number of contributors
5. Check the table that contains all contributors to see if the new contributor was added

**Expected behavior**
The newly added contributor should show in the table in readme file

**Additional context**
Interesting enough the file containing the json for all contributors gets updated as intended but the readme isn't updated.

**Comment by Beardless-sheik** [comment]
@OlivierJM I tried to mimic this behaviour on a local branch and the bot didn't even create a oull request. Any ideas?

**Comment by malgamves** [comment]
Same, any progress here?

**Comment by malgamves** [comment]
This is working. Only works when triggered by repo owner on GitHub not locally. Closing
