### ISSUE TITLE
Netlify showing a 404 page on different route other than home

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#116]
Another thing, I just noticed is that Netlify is acting up on the route surprisingly

**To do**

- Help find what is causing this
- Fix the navbar links
- Replace custom links with <NavLink/>

If you plan to work on this issue, start working from the linked Pull Request

_Originally posted by @OlivierJM in https://github.com/devconzm/devconzm/pull/115#issuecomment-519399113_

**Comment by malgamves** [comment]
Cool, this was fixed!
