### ISSUE TITLE
Navbar should persist on all routes

### ISSUE THREAD

**Issue by malgamves** [devconzm/devconzm#117]
**Describe the bug**
The Code of Conduct route does not have the navbar which makes it impossible to navigate back to the home page. 

**To Reproduce**
1. Go to 'devcon.co.zm'
2. Click on 'Code of Conduct'
3. See error - can't nagivate back to home or other routes.

**Expected behavior**
The navbar should appear on all routes as it does on the speaker route for example. It's worth adding "home" to the navbar too

**Comment by OlivierJM** [comment]
I am going to work on this.

**Comment by malgamves** [comment]
I think #121 fixed this @OlivierJM

**Comment by OlivierJM** [comment]
> I think #121 fixed this @OlivierJM

Yeah I noticed, it is currently linking to a wrong id, I will push in for a fix.
