### ISSUE TITLE
Embed Video on about section

### ISSUE THREAD

**Issue by malgamves** [devconzm/devconzm#119]
I think we could do well to add the promo video to the bottom of the about section of our website. [Link to video](https://www.linkedin.com/feed/update/urn:li:activity:6565574708425830400)

**Comment by k9uma** [comment]
Can I post the video on our Youtube page instead?

**Comment by malgamves** [comment]
Yes, it would make it much easier to embed.

**Comment by k9uma** [comment]
> 
> 
> Yes, it would make it much easier to embed.

<iframe width="560" height="315" src="https://www.youtube.com/embed/k4q6gGcslA0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by malgamves** [comment]
Perfect, thanks!

**Comment by k9uma** [comment]
Welcome
