### ISSUE TITLE
Progressive Web App Support

### ISSUE THREAD

**Issue by malgamves** [devconzm/devconzm#120]
When I think about it, the pro's out weigh the con's of implementing PWA support for the site. What are your thoughts @OlivierJM ?

**Comment by OlivierJM** [comment]
> When I think about it, the pro's out weigh the con's of implementing PWA support for the site. What are your thoughts @OlivierJM ?

Yeah that is true, we can clean up most of accessibility issues and implement the PWA, this won't be hard since we already have the serviceWorkers in place. 
We can start working towards this.

**Comment by malgamves** [comment]
Awesome, what else would be required?

**Comment by OlivierJM** [comment]
> Awesome, what else would be required?

I think first step, is to run a lighthouse audit.
check here for the report https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.devcon.co.zm/
It seems mostly we have an issue with performance, we can start working on that, the have a proper manifest file, the register the serviceWorker that we currently have.

**Comment by malgamves** [comment]
Hey, can we create an issue for each item we need to improve based on the lighthouse analysis?

> > Awesome, what else would be required?
> 
> I think first step, is to run a lighthouse audit.
> check here for the report https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.devcon.co.zm/
> It seems mostly we have an issue with performance, we can start working on that, the have a proper manifest file, the register the serviceWorker that we currently have.

Can we create issues for item that comes up from the lighthouse analysis?

**Comment by OlivierJM** [comment]
> Hey, can we create an issue for each item we need to improve based on the lighthouse analysis?
> 
> > > Awesome, what else would be required?
> > 
> > 
> > I think first step, is to run a lighthouse audit.
> > check here for the report https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.devcon.co.zm/
> > It seems mostly we have an issue with performance, we can start working on that, the have a proper manifest file, the register the serviceWorker that we currently have.
> 
> Can we create issues for item that comes up from the lighthouse analysis?

Yeah sure let's me that.
