### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#123]
> Awesome, what else would be required?

Originally discussed in this issue #120 

I think first step, is to run a lighthouse audit.
check here for the report https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://www.devcon.co.zm/
It seems mostly we have an issue with performance, we can start working on that, the have a proper manifest file, the register the serviceWorker that we currently have.

_Originally posted by @OlivierJM in https://github.com/devconzm/devconzm/issues/120#issuecomment-522257494_

**Comment by OlivierJM** [comment]
Here are first things to get started with on this.

- Lazy load components
- Lazy load images
- Update the `manifest.json`
- add a meta tag #112 
- Test cross-browser support #122 

React.lazy and React.Suspense can help on the lazy loading but we would need a well creafted loading component to show while these are about to show.
Most of our images are heavy, we might need to find a CDN for them or properly load them in their respective components.

**Comment by OlivierJM** [comment]
If you are interested, fixing issues related to this will get you a free ticket.

**Comment by Big-Zude** [comment]
> If you are interested, fixing issues related to this will get you a free ticket.

i want to try this out and hopefully complete it.

**Comment by OlivierJM** [comment]
> If you are interested, fixing issues related to this will get you a free ticket.
> 
> i want to try this out and hopefully complete it.

Awesome

**Comment by Chizzoz** [comment]
Morning @OlivierJM ! Created a PR for this issue, kindly check here #130
