### ISSUE TITLE
Add Asikana network logo

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#126]
This logo needs to be added as our partners

![Asikana Logo Updated](https://user-images.githubusercontent.com/11255454/63378822-52e72680-c393-11e9-9b81-d1a90f8b45d5.jpg)

**Comment by k9uma** [comment]
This logo needs to be added as well....

![1200px-Amazon_Web_Services_Logo svg](https://user-images.githubusercontent.com/12296763/63404242-b77da200-c3e2-11e9-8ee8-f484734d3909.png)

**Comment by kazashim** [comment]
> This logo needs to be added as our partners
> 
> ![Asikana Logo Updated](https://user-images.githubusercontent.com/11255454/63378822-52e72680-c393-11e9-9b81-d1a90f8b45d5.jpg)

@OlivierJM I have added Asikana Network logo
