### ISSUE TITLE
Add Speakers to Website

### ISSUE THREAD

**Issue by k9uma** [devconzm/devconzm#129]
**Describe the solution you'd like**
The speakers page should contain the following;
Speaker Name
Speaker Position and Company
Speaker Picture

**Additional context**
Speaker Information can be found in this [folder](https://drive.google.com/open?id=1Vm2_cQ2q9qTwQCub-XDcBKUopvLK0VLi)

**Comment by OlivierJM** [comment]
Fixed the issue here #134

**Comment by k9uma** [comment]
Mwaamba Mugala should change to Mwaaba Mugala
Shakerrie Allmond is the Regional Director at The Virtual Doctors and her talk is Impact of Health Technology

**Comment by OlivierJM** [comment]
For more visibility, I have made the above comment as its own issue, plus I can also work on it tomorrow
