### ISSUE TITLE
Background Image choice may need revisiting

### ISSUE THREAD

**Issue by djtwenty6** [devconzm/devconzm#13]
**Is your feature request related to a problem? Please describe.**
The background on the home page does not look Zambian enough, if at all it is.

**Describe the solution you'd like**
It would be nice to put an image of a recognizable landmark.

**Describe alternatives you've considered**
As cliche as it may be, the Victoria Falls may be a clearer option. Gray scale.

**Additional context**

**Comment by OlivierJM** [comment]
Thanks @djtwenty6 for pointing this out.

@k9uma It would be so great to have a vic falls pic on that home page.

**Comment by k9uma** [comment]
Okay, taken note of that, we will have some alternatives, piggybacking ideas on design will be difficult though... So revisions will have to be periodical.
