### ISSUE TITLE
Live Stream button

### ISSUE THREAD

**Issue by djtwenty6** [devconzm/devconzm#14]
**Is your feature request related to a problem? Please describe.**
If there will be a live stream, it would be good to have a button/link to it in the menu bar atop.

**Describe the solution you'd like**
The button could be glowing/animated (red in colour), with 'Watch Live' written on it. It could be placed where the current 'Devcon19' button is, and the decon button moved to the left edge of the homepage.

**Describe alternatives you've considered**
None.

**Additional context**
![500_F_33050826_fGEV9vHFpOk6KyPRbkHx8BfjQsFRW6z2](https://user-images.githubusercontent.com/32264045/57448613-16674300-725a-11e9-8c6c-bbd81a0b3d53.jpg)

**Comment by OlivierJM** [comment]
@leemlwando want to offer us a streaming service on the conference day so this would definitely be a thing to have.

**Comment by OlivierJM** [comment]
@allcontributors please add @djtwenty6 for ideas

**Comment by malgamves** [comment]
We should probably look into something like [resream.io](https://restream.io/) as an alternative too
