### ISSUE TITLE
Mwaamba Mugala should change to Mwaaba Mugala

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#140]
Mwaamba Mugala should change to Mwaaba Mugala
Shakerrie Allmond is the Regional Director at The Virtual Doctors and her talk is Impact of Health Technology

_Originally posted by @k9uma in https://github.com/devconzm/devconzm/issues/129#issuecomment-530342267_

**Comment by Beardless-sheik** [comment]
#141 and #144 address this I think
