### ISSUE TITLE
[Proposal] Switch back to default branch

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#156]
This #88 PR was introduced as some major breaks that were in the repo and the only quicker way was to work on a separate one. 
I have levelled up the two branches master === releases so we can master the default branch once again.
This will need thorough testing to make sure it doesn't break anything.

**Comment by k9uma** [comment]
Approved... Lets go ahead

**Comment by OlivierJM** [comment]
> Approved... Lets go ahead

Thanks @k9uma, I am collecting everything that needs to be worked on, If it is all good I can get started on all these on Sunday.

**Comment by OlivierJM** [comment]
This is resolved, am closing the issue.
