### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#2]
This is currently built in react but since I would like contributions from everyone else, I will keep this issue open for other suggestions.
we can go with the agreed and what everyone would be comfortable with.

What to keep in mind is that, this site isn't data heavy and probably won't contain any data so we are likely not to need any framework(though the development becomes much easier with one.)

**Comment by OlivierJM** [comment]
The site also uses bootstrap, this is also open for discussion

**Comment by k9uma** [comment]
I think a lot of us are already comfortable enough to work with React, Also Bootstrap is fine...

**Comment by OlivierJM** [comment]
That is great, then we can continue with the current setup.

**Comment by malgamves** [comment]
I think thats fine. I know how to use React on surface level plus seeing as most of the work will be done by you its better to go for what your comfortable with. I'll mostly help with content and minor design touch ups and not much on structure.

**Comment by OlivierJM** [comment]
Awesome, that is great.
Those touch ups and minor designs are the most important part.  Thanks

**Comment by OlivierJM** [comment]
@allcontributors please add @OlivierJM for code doc

**Comment by OlivierJM** [comment]
@allcontributors please add @k9uma @Mulency @makayi @malgamves for eventOrganizing ideas

**Comment by OlivierJM** [comment]
@allcontributors please add @k9uma for eventOrganizing ideas
@allcontributors please add @Mulency  for eventOrganizing ideas
@allcontributors please add @makayi for eventOrganizing ideas
@allcontributors please add @malgamves for eventOrganizing ideas

**Comment by OlivierJM** [comment]
@allcontributors please add @k9uma for eventOrganizing ideas

**Comment by OlivierJM** [comment]
@allcontributors please add @Mulency for eventOrganizing ideas

**Comment by OlivierJM** [comment]
@allcontributors please add @makayi for eventOrganizing ideas

**Comment by OlivierJM** [comment]
@allcontributors please add @malgamves for eventOrganizing ideas
