### ISSUE TITLE
proper image alignment

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#3]
The top layout should match the indicated image below

![IMG_1732](https://user-images.githubusercontent.com/11255454/57190692-adac5d80-6f1d-11e9-97f0-3e67855709f7.PNG)

**Comment by malgamves** [comment]
Might be a typo - I think it should be *software developer* conference.  Might be wrong

**Comment by OlivierJM** [comment]
Just noticed that, it needs to be changed

**Comment by OlivierJM** [comment]
this was fixed in this PR #47 
I am closing it for now, feel free to reopen it when there is need.
