### ISSUE TITLE
add a coming soon page [urgent]

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#43]
As we are still building the whole site we will need a coming soon page, it can only contain things like venue and date for the conference.
any pretty good design is welcome for now

**Comment by OlivierJM** [comment]
This page should basically contain, basic information about the conference which can be obtained at the current site in the repo description.

**Comment by OlivierJM** [comment]
The need for this is so that we deploy the site and make it public as we are still working on the actual site.

**Comment by k9uma** [comment]
There havent been any takers for this one? Maybe we can ask Kumbu to design an image to place on the site? With all the information

**Comment by OlivierJM** [comment]
Sure do that, actually it would be easier for contributors if there was a design for this.

**Comment by k9uma** [comment]
Can we use the waterfalls picture he made?

**Comment by OlivierJM** [comment]
Did we agree on that ? I remember Daniel being skeptic about it.

**Comment by k9uma** [comment]
He okayed it I think

**Comment by OlivierJM** [comment]
Awesome, I will create an issue for that.

**Comment by k9uma** [comment]
Since we deployed the release, do we still need this?

**Comment by OlivierJM** [comment]
No we don't, thank you, 

I am closing this.
