### ISSUE TITLE
sponsors logos

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#45]
We will need to add sponsors logos on the site

**Comment by OlivierJM** [comment]
@k9uma I didn't find a folder in the drive where there are logos, can we link them here?

**Comment by k9uma** [comment]
I dont think we have a folder for those logos just yet, let me create it

**Comment by OlivierJM** [comment]
alright when you create it, you can re-open this issue or create a new one so that someone can work on it.
