### ISSUE TITLE
Add a proper readme 

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#5]
Things to include:

- [x] What this is
- [x] Technologies it uses
- [x] Contribution guide
- [x] Link to the live site.
- [x] List of outside contributors
- [x] Conference Code of Conduct

**Comment by malgamves** [comment]
This is perfect - I think we can pass this on to a community member. A good way to get them started contributing to open source tech. Post the issue on the group maybe?

**Comment by OlivierJM** [comment]
I totally agree with you on this one.

**Comment by malgamves** [comment]
Yup, really good opportunity.

**Comment by Peterchama** [comment]
this is   nice  it will give a platform for some us the who are learning to contribute and learn more from others

**Comment by killian-coder** [comment]
This is great i will definitely contribute

**Comment by OlivierJM** [comment]
Feel free to work on this.

you can find a contribution guide [here](https://github.com/devconzm/devconzm/blob/master/CONTRIBUTING.md)  and a code of conduct [here](https://github.com/devconzm/devconzm/blob/master/CODE_OF_CONDUCT.md)

**Comment by LuisRoyZulu06** [comment]
This is a cool-platform to learn!

**Comment by mandrigo** [comment]
this is awesome, would love to contribute something.

**Comment by OlivierJM** [comment]
> Feel free to work on this.
> 
> you can find a contribution guide [here](https://github.com/devconzm/devconzm/blob/master/CONTRIBUTING.md) and a code of conduct [here](https://github.com/devconzm/devconzm/blob/master/CODE_OF_CONDUCT.md)

Check this and let me know other questions you might have ☝🏾

**Comment by Big-Zude** [comment]
can i jump on this @OlivierJM

**Comment by OlivierJM** [comment]
Please do that

**Comment by OlivierJM** [comment]
Note: This issue was worked on here #12 but if you have any improvements its all welcome, I will keep it open

**Comment by Big-Zude** [comment]
alright

**Comment by OlivierJM** [comment]
#16
