### ISSUE TITLE
Sections stretching too wide on large screens

### ISSUE THREAD

**Issue by Chizzoz** [devconzm/devconzm#51]
**Describe the bug**
The sections in web page have a chevron like design. With screen width of up to about 1200px, this looks good, but above that, like on wide screens, this design stretches and does not look as good as on smaller screens.

This could be maintained or the chevron design can be confined in the section containers.

**To Reproduce**
1. Open page on widescreen, larger than 1200px width.

**Expected behavior**
Section design will stretch to fill the whole screen

**Screenshots**
On the left is initial design and on the right is design with chevrons confined to section containers
![screencapture-side-by-side](https://user-images.githubusercontent.com/17289498/57975651-3bcc1d80-79cd-11e9-99df-f281d62c554e.jpg)

**Additional context**
An alternative option is kind of a combination of both designs in side-by-side screenshots above, that is, have chevrons confined to section containers with a maximum width, but have a stretched background, as is with the image in header.

Feel free to contribute on this issue.

**Comment by ikayz** [comment]
If that was implemented using Bootstrap. I think I know the problem that's causing it.

**Comment by OlivierJM** [comment]
can you work on this ?

**Comment by ikayz** [comment]
Sure thing, will debug and hopefully fix it 😁

**Comment by OlivierJM** [comment]
awesome, I will be looking forward for a PR 😀

**Comment by ikayz** [comment]
![bug-1](https://user-images.githubusercontent.com/31007212/58081742-de46f500-7bb5-11e9-97b3-a19f656ad8b9.png)
My screen maxes out at 1080p but I used different screen simulators and that's the bug I came across. I'll instead add classes to specify extra small, small, medium, and large screens. The only class specified is for medium screens. Also the mobile bugs like text kissing the edge of the left screen, I'll work on that...

**Comment by OlivierJM** [comment]
Thanks for that, make sure you update with the origin to match with the recent updates from @Chizzoz

**Comment by ikayz** [comment]
I'll add on top of what @Chizzoz  wrote. Just expanding on it.

**Comment by OlivierJM** [comment]
Awesome thanks

**Comment by Chizzoz** [comment]
@ikayz and @OlivierJM is this still an issue?

**Comment by malgamves** [comment]
This seems to have been fixed now
