### ISSUE TITLE
images on mobile

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#52]
**Describe the bug**
on a small screen images are not responsive, this will push users to scroll horizontally and are likely not to see somethings.

**To Reproduce**
1. Go to https://devconzm.netlify.com
2. reduce the screen width or better navigate to it on a mobile phone
3. check the header and image of the conference description
4. check how it looks

**Expected behavior**
The best would be to make sure images are very responsive

**Screenshots**
this is the view on small screen 
![Screenshot 2019-05-19 at 9 02 22 AM](https://user-images.githubusercontent.com/11255454/57978873-5e822480-7a15-11e9-887c-5aee2f4ce13e.png)

**Comment by AbednegoTM** [comment]
has this issue been solved

**Comment by OlivierJM** [comment]
Hi Abed,

When I check on my ka small phone the image on the left still doesn’t resize perfectly. 
Try it and see if you can alter it in anyway.

**Comment by OlivierJM** [comment]
Another approach could be to hide it all together on smallest devices.

**Comment by AbednegoTM** [comment]
Okay can make a PR with mobile break points were mobile styles can live. apparently browser mobile view (devtools) looks fine somehow , unless on very small screen. so i can take up this issue, do i have a go ahead .

**Comment by OlivierJM** [comment]
Heyyy @AbednegoTM  you have a go ahead, sorry for the late reply.
I will mark this issue as claimed. Thanks

**Comment by OlivierJM** [comment]
I am closing this issue as it has been resolved in the referred PR.
Feel free to reopen it
