### ISSUE TITLE
toggle menu in the header on small screen 

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#53]
**Describe the bug**
on small screen the menu is hidden and can't be triggered to show

**To Reproduce**
1. Go to https://devconzm.netlify.com preferrably on a mobile device
2. reduce the screen size
3. click on the menu icon
4. The menu is not triggered

**Expected behavior**
The menu is supposed to show so that viewers on mobile devices can navigate the size in a smooth way

**Screenshots**
the screen shot below shows this 
![Screenshot 2019-05-19 at 9 02 22 AM](https://user-images.githubusercontent.com/11255454/57978972-f59bac00-7a16-11e9-9c34-c6c0e81a59cb.png)

**Suggested fix **
1. link the bootstrap cdn in the index.html
2. make sure this issue is also fixed #52

**Comment by Chizzoz** [comment]
I noticed this as well, was about to raise the same issue. It seems that the hamburger menu Bootstrap feature depends on JQuery library, I have implemented a fix, will create PR asap. But a new problem has been created, menu is a bit off screen, I think it has to do with the Bootstrap Flex layout.

**Comment by Chizzoz** [comment]
Notice the width of everything except header and white space on the right
![screencapture-localhost-3000-2019-05-19-15_48_51](https://user-images.githubusercontent.com/17289498/57983052-b50b5500-7a4d-11e9-8b91-2abc35243ba0.png)

**Comment by OlivierJM** [comment]
> Notice the width of everything except header and white space on the right
> ![screencapture-localhost-3000-2019-05-19-15_48_51](https://user-images.githubusercontent.com/17289498/57983052-b50b5500-7a4d-11e9-8b91-2abc35243ba0.png)

should we create a new issue from this one ? it seems a bit different I want to close this one

**Comment by CHISANGA1** [comment]
hello.i'm a beginner.

 i have been following through this project and i have an observation which maybe specific to my device (i am not sure) which is the galaxy s6 edge plus. The content on the about section is way to down the edge which is making reading difficult. the words are not almost vanishing into the edges on the right.

**Comment by OlivierJM** [comment]
Hi Chisanga, thanks for noting that.
Can you kindly share a screenshot of that.

**Comment by CHISANGA1** [comment]
![Screenshot_20190521-131936](https://user-images.githubusercontent.com/39368651/58093333-92547a00-7bce-11e9-94ee-0aed3bcf9eb9.png)

**Comment by CHISANGA1** [comment]
so that section on my phone is way to into the edges. especially on the left side

**Comment by OlivierJM** [comment]
I see what you, it’s like it needs some padding around this paragraph. 
Feel free to fix this, since it’s your first time check the contribution guide, I will be looking forward to your pull request

**Comment by CHISANGA1** [comment]
thanks..

**Comment by Chizzoz** [comment]
I believe this was sorted

**Comment by CHISANGA1** [comment]
Yes. It's okay now

**Comment by OlivierJM** [comment]
closing this issue.
