### ISSUE TITLE
Add an image slider

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#55]
**Is your feature request related to a problem? Please describe.**
Not really a problem but something worth having on the site

**Describe the solution you'd like**
According to the initial design of the site, it looks like we need to have a slider for images, not so sure exactly which images we are supposed to have there, i will follow this up

**Describe alternatives you've considered**
an alternative is to leave the way it is now, it looks just fine.

**Additional context**
The slider would need to be very slick and smooth

**Comment by OlivierJM** [comment]
we could have there maybe some photos of the last conference, this is just a thought.

**Comment by k9uma** [comment]
I am not sure, I think its worth thinking about...

**Comment by k9uma** [comment]
For now, we can leave it as it is

**Comment by OlivierJM** [comment]
I think so too.

**Comment by OlivierJM** [comment]
I will go ahead and close this, feel free to re-open it when needed.
