### ISSUE TITLE
remove packages that aren't needed 

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#56]
in the package.json there are packages which we don't need, the best is to get rid of them
you can check here 
this one 
https://github.com/devconzm/devconzm/blob/1c649316efefe83b0ffe23912a1903b11cad8351/package.json#L11

and this one 
https://github.com/devconzm/devconzm/blob/1c649316efefe83b0ffe23912a1903b11cad8351/package.json#L10

**Comment by Big-Zude** [comment]
so all i need to do is delete those lines from the package.json and then commit it to my folked repo and then create a pull request?

**Comment by OlivierJM** [comment]
That is basically what is needed.

check also this issue #58  and see if you can do them together since they are related.

**Comment by OlivierJM** [comment]
let me also know when you want to work on specific issue so that I add an issue-claimed label so that someone else doesn't work on it while you are working on it.

**Comment by Big-Zude** [comment]
alright thanks

**Comment by OlivierJM** [comment]
> so all i need to do is delete those lines from the package.json and then commit it to my folked repo and then create a pull request?

@Big-Zude when you remove the lines make sure you run either `yarn ` or `npm install` then start the app by either `yarn start` or `npm start ` to make sure everything is working fine.

**Comment by Big-Zude** [comment]
i will do that thanks

**Comment by OlivierJM** [comment]
Cool am adding an issue-claimed here then.

**Comment by Big-Zude** [comment]
i think i messed, i need you to review it and give me feedback

**Comment by OlivierJM** [comment]
sure send a pull request, I will review it.
