### ISSUE TITLE
remove the contactus component

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#57]
this component was added earlier as part of the home page but according to the design we don't need it, the best is to remove it.
it can be found [here](https://github.com/devconzm/devconzm/blob/master/src/components/ContactUs.js) 
it was removed from the App.js in this pull request #42

**Comment by Big-Zude** [comment]
is this still open?

**Comment by OlivierJM** [comment]
Yes it is.

**Comment by Chizzoz** [comment]
Is this issue still open?
