### ISSUE TITLE
remove the lock files

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#58]
It is understood that we use different package managers and it shouldn't matter because we can't force usage of one.
to avoid package versions conflicting in lock files it will be good to keep the lock files in the `.gitignore`
files to include are these: 
- package.lock.json
- yarn.lock

This will make it independent of which package manager one uses.

**Comment by tumbone** [comment]
Hi @Big-Zude are you looking at this?

**Comment by OlivierJM** [comment]
This was worked on but the issue wasn't fully fixed, Its why i kept it open.
Feel free to work on it.

**Comment by tumbone** [comment]
Ok cool will do.

**Comment by OlivierJM** [comment]
I am closing this down, feel free to reopen it if there is need

**Comment by Big-Zude** [comment]
@OlivierJM have you fixed the issue of the packages?
please when you do give me feedback on how its done.

**Comment by OlivierJM** [comment]
Yeah I fixed it.
running `npm audit` reported a lot of vulnerabilities, and most of them were caused by the `react-scipts` package, so I did these steps:
1. I removed one lock file(yarn.lock)
2. I deleted the node_modules directory
3. I ran `npm install `
4. I updated the react-script package

and did some other clean ups but this fixed the vulnerabilities.

**Comment by Big-Zude** [comment]
alright thanks

**Comment by tumbone** [comment]
@OlivierJM we still need to remove the reference to package-lock.json from the .gitignore file otherwise the existing lock file will never be updated. I'll create a PR for this.

**Comment by OlivierJM** [comment]
Sure thanks.
