### ISSUE TITLE
add more tests

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#59]
so far we have been relying on netlify continuous deployment for a deploy preview to make sure that changes sent in pull requests aren't breaking anything we don't intend to break.

This is not fault proof, it will be good to have some tests that can against each pull requests for changes.
I added basic tests to give a snapshot of how tests should be written, an example can be found starting from this line
and the files in the __tests__ https://github.com/devconzm/devconzm/blob/1c649316efefe83b0ffe23912a1903b11cad8351/src/__tests__/header.test.js#L5

**Comment by tumbone** [comment]
I can have a look at this

**Comment by OlivierJM** [comment]
I will appreciate.
I haven't had enough time for this one 😞
