### ISSUE TITLE
Maybe "Agenda" link should also go?

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#66]
Maybe "Agenda" link should also go?

_Originally posted by @Chizzoz in https://github.com/devconzm/devconzm/pull/65#issuecomment-494297217_

**Comment by OlivierJM** [comment]
what do you guys think on the agenda in the header ?

**Comment by k9uma** [comment]
We can remove it for now... It can come when we announce the schedule

**Comment by OlivierJM** [comment]
cool.

**Comment by OlivierJM** [comment]
removed this, am closing this now.
