### ISSUE TITLE
concern over the repo size

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#76]
The repo size has grown from less than 1mb to over 27mb 🤔 I don't know exactly why it is so, but anyone who is interested to investigate why ideas are welcome

**Comment by OlivierJM** [comment]
we have few images in the repo which are very light but as part of optimization #67 we should be thinking of hosting the images over a cdn to provide a light experience and keeping the minimum size of the repo.
we also have some code that aren't being used, I am not sure how webpack tree shaking is set up in the create-react-app but we might need to manually get rid off any part of code that is not being used.

**Comment by k9uma** [comment]
We really need a quality assurance person lol

**Comment by OlivierJM** [comment]
I will investigate on this.

**Comment by malgamves** [comment]
@OlivierJM any luck on this?

**Comment by OlivierJM** [comment]
@malgamves @k9uma my apologies for taking long to take some actions 

I just noticed this has gotten worse, we are above 60mb repo size, few things that can be done as initial steps:

- use a CDN like [Cloudinary](https://cloudinary.com/pricing) or S3 to host all images
- use an a bot that checks every PR for repo size 
- use an imageOptimizer bot like this https://github.com/marketplace/imgbot

I can work on all these next week to try and see if we can bring it down to less than 10mb and we can.
