### ISSUE TITLE
Add resources from last year's DevCon18 to the website

### ISSUE THREAD

**Issue by WillzMu** [devconzm/devconzm#77]
It would be good to have any resources that were shared from last year's DevConZM18 event for people to recap on what lessons that were given and for those that may have missed out on the event. 

Alternative solution
The resources could be hosted on a GitHub repo then there maybe no need to create a separate page.

**Comment by k9uma** [comment]
On it

**Comment by OlivierJM** [comment]
@allcontributors please add @WillzMu for ideas

**Comment by WillzMu** [comment]
thanks @OlivierJM

**Comment by malgamves** [comment]
I think we need an assets repository. Thoughts @OlivierJM and @k9uma ?
