### ISSUE TITLE
change background image

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm#80]
**Is your feature request related to a problem? Please describe.**
This issue is related to this #13 

**Describe the solution you'd like**
we need to change the current image background to one that properly defines Zambia
The image can be found here https://drive.google.com/drive/folders/1-qZdFJX1KzhEvGTNFcCaZ8XOUFIqOetZ

**Describe alternatives you've considered**
the alternative is to have any background that is more culture driven

**Additional context**
Though there might be some styling that needs to accompany this change you would basically need to just replace the current image with the one shared above

**Comment by locness3** [comment]
Would be a simple CSS change, no ?

**Comment by OlivierJM** [comment]
I really believe it is a matter of alignment because and responsiveness, this is just a replacement of the current image.

**Comment by locness3** [comment]
Ok. WHich of the images would you like ?

**Comment by OlivierJM** [comment]
This is the image https://drive.google.com/drive/folders/1-qZdFJX1KzhEvGTNFcCaZ8XOUFIqOetZ

**Comment by locness3** [comment]
Which one of the folder ?

**Comment by OlivierJM** [comment]
![Devcon 19 web background1](https://user-images.githubusercontent.com/11255454/58532839-0dc5b500-81e7-11e9-9448-402ba4a78e95.png)


> This is the image https://drive.google.com/drive/folders/1-qZdFJX1KzhEvGTNFcCaZ8XOUFIqOetZ

**Comment by OlivierJM** [comment]
> Which one of the folder ?

The one shared above

**Comment by locness3** [comment]
Ok

**Comment by locness3** [comment]
How can I preview my chenges ? I have never had experience with React, and Netlify doesn't seem to work for me.

**Comment by OlivierJM** [comment]
> How can I preview my chenges ? I have never had experience with React, and Netlify doesn't seem to work for me.

have you checked the contributing guide? netflify will only work on a fully working pull request.

**Comment by OlivierJM** [comment]
if you clone this repo, you would need to first install packages using npm `npm install` and you do  `npm run start` this should be open the site in the browser if there are no errors

**Comment by locness3** [comment]
Oh ok

**Comment by OlivierJM** [comment]
> > How can I preview my chenges ? I have never had experience with React, and Netlify doesn't seem to work for me.
> 
> have you checked the contributing guide? netflify will only work on a fully working pull request.

Netlify seems to be erring, I will check that out.

**Comment by locness3** [comment]
Seems to be a probel with package.json, doesn't work on my machine either

**Comment by OlivierJM** [comment]
let me check it, I will give you feedback soon.

**Comment by OlivierJM** [comment]
I fixed the failing build, you should be able to preview your changes when you submit a pull request.

**Comment by k9uma** [comment]
Hey @locness3 did you manage with the background change?

**Comment by OlivierJM** [comment]
The background was successfully changed, there was still an issue of contrast, to make the wording more visible in contrast to the background. check it here #84

**Comment by malgamves** [comment]
What options do we have for a new background image?
