### ISSUE TITLE
Using semantic tags correctly

### ISSUE THREAD

**Issue by locness3** [devconzm/devconzm#81]
**Describe the bug**
The page header (with nav, tagline, and call to action) is wrapped in an nav tag. But it isn't a navbar.

**Expected behavior**
I expect only the real nav to use the nav tag, not the rest of the header.

**Desktop (please complete the following information):**
 - OS: macOS 10.11.6
 - Browser Firefox
 - Version 67.0

**Additional context**
You should fix this for screen readers. Focusing the header, it will read "navbar".

**Comment by OlivierJM** [comment]
Thanks for filing in this.
Would you love to work on this ?

**Comment by OlivierJM** [comment]
@allcontributors please add @locness3 for bug

**Comment by locness3** [comment]
> Thanks for filing in this.
> Would you love to work on this ?

truly sorry, but no.

**Comment by OlivierJM** [comment]
> > Thanks for filing in this.
> > Would you love to work on this ?
> 
> truly sorry, but no.

Alright.
