### ISSUE TITLE
Changing repo name

### ISSUE THREAD

**Issue by malgamves** [devconzm/devconzm#9]
Could we change the repo name to just **devconzm** so we dont have to make a new one every year?

**Comment by OlivierJM** [comment]
Ohhhh yeah that would be better, let's hear what others have to say about this.

**Comment by malgamves** [comment]
Hey I cant add labels, what are my org permissions?
I agree
https://github.com/devconzm/devconzm19/issues/9#issuecomment-489935953

**Comment by OlivierJM** [comment]
let me check on your permissions.

**Comment by OlivierJM** [comment]
You are now the org owner 😀

**Comment by k9uma** [comment]
We can change the name

**Comment by OlivierJM** [comment]
Alright I will go ahead and change the name.

**Comment by OlivierJM** [comment]
I will close this for now, feel free to re-open it
