### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by k9uma** [devconzm/devconzm#90]
Add a Favicon for the release application

**Comment by Beardless-sheik** [comment]
Do we have a design for it already?

**Comment by OlivierJM** [comment]
Try and see if you can find them here https://drive.google.com/drive/folders/1-edCcmkQPXrmgG1VfFAxXawgZXFwYpjE?usp=sharing

**Comment by OlivierJM** [comment]
@Beardless-sheik can you use this logo as a favicon it only needs to be reduced to 50X50 
@k9uma do you approve this to be used?
![sticker](https://user-images.githubusercontent.com/11255454/60827557-c4d32a00-a1b0-11e9-88df-dee79f61dcdd.png)

**Comment by Beardless-sheik** [comment]
I can use that........... @k9uma is it ok with you?

**Comment by OlivierJM** [comment]
> I can use that........... @k9uma is it ok with you?

Please go ahead, just try and bring down the size to 50X50 to properly fit the favicon size

**Comment by Chizzoz** [comment]
Evening gents! Jumped in on this issue. I have created a PR for you to look at.

**Comment by OlivierJM** [comment]
#94  Once again Thanks @Chizzoz

**Comment by k9uma** [comment]
> I can use that........... @k9uma is it ok with you?

Sorry only seeing this now... You can go ahead

**Comment by OlivierJM** [comment]
Closing this, @Chizzoz worked on it.
