### ISSUE TITLE
Setting up remote version

### ISSUE THREAD

**Issue by geraldMaboshe** [devconzm/devconzm#91]
I'm having trouble setting up a remote version of my forked repo. I'm getting 
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
@OlivierJM may you help?

**Comment by OlivierJM** [comment]
Hi @geraldMaboshe thanks for reaching out.
If you are cloning your forked repo, use this link https://github.com/geraldMaboshe/devconzm

`git clone https://github.com/geraldMaboshe/devconzm`   
that should be able to work, let me know if the error persist.

**Comment by geraldMaboshe** [comment]
I'm still getting the same error

**Comment by OlivierJM** [comment]
This is likely a windows issue, my guess
Try and type the whole line from git ... don't copy and paste it, if it doesnt work share the screenshot with me

**Comment by geraldMaboshe** [comment]
![Screenshot from 2019-07-08 20-10-30](https://user-images.githubusercontent.com/41299580/60832605-922f2e80-a1bc-11e9-9250-aaf4ecf8a214.png)

**Comment by OlivierJM** [comment]
ahhhh I see, so it is not when cloning 🤔

Cool, feel free to skip for now, make all the changes you want to make and when you are done push the changes to your fork and from your fork create a Pull Request that points to the devconzm(releases branch). I will pick up changes from there.

**Comment by geraldMaboshe** [comment]
How do I make the pr point to the release one?

**Comment by OlivierJM** [comment]
When creating the PR, it will prompt you which branch to make the base, if you dont manage, go ahead and point it to the master, I will do the reconciling from my side.
